
#' Set personal access token by writing it into environment variables.
#'
#' @param pat A string containing the personal access token generated on Github.
#'
#' Not very secure. At some point I should use the approach of the gh package
gh_set_pat = function(pat) {
  # Used by these API functions
  Sys.setenv(GITHUB_PAT = pat)

  # Used by github cli
  Sys.setenv(GITHUB_TOKEN = pat)

}

#' Get personal access token that was previously set b gh_set_pat.
gh_pat = function() {
  Sys.getenv("GITHUB_PAT")
}

gh_list_run_jobs = function(repo, runid, pat=gh_pat()) {
  #https://api.github.com/repos/OWNER/REPO/actions/runs/RUN_ID/jobs
  gh_get(paste0("repos/", repo,"/actions/runs/",runid,"/jobs"),pat)$jobs
}

#' Return all workflow runs
gh_list_runs = function(repo, pat=gh_pat()) {
  #https://api.github.com/repos/OWNER/REPO/actions/runs
  gh_get(paste0("repos/", repo,"/actions/runs"),pat)$workflow_runs

}

#' Return all workflows of the specified repo
gh_list_workflows = function(repo, pat = gh_pat()) {
  #https://api.github.com/repos/OWNER/REPO/actions/workflows
  gh_get(paste0("repos/", repo,"/actions/workflows"),pat)$workflows
}


#' Trigger the specified workflow
#'
#' Only works if the workflow YAML file sets
#'
#' on:
#'   workflow_dispatch:
#'
#' @param repo The repository name in format user/reponame.
#' @param name The name of the workflow. If NULL use the first workflow
#' @param branch The Github branch. By default "main"
#' @param inputs Not yet tested. Potential input parameters passed to the workflow.
#'
gh_run_workflow = function(repo,name=NULL,branch="main", inputs=NULL, pat = gh_pat()) {
  restore.point("gh_run_workflow")

  workflows = gh_list_workflows(repo, pat)

  if (NROW(workflows)==0) {
    cat("\nNo workflow found.")
    return(NULL)
  }

  row = 1
  if (!is.null(name)) {
    row = match(name, workflows$name)
  }

  wf_id = workflows$id[row]

  values = list(ref=branch)
  if (!is.null(inputs))
    values$inputs = inputs
  #https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/dispatches \
  res = gh_post(paste0("repos/", repo,"/actions/workflows/",wf_id,"/dispatches"),values=values, pat = pat)

  res

}

set_up_py_for_secrets = function() {
  py_install("pynacl")
}

# Uses python
gh_set_secret = function(repo, name, value, pat = Sys.getenv("GITHUB_PAT")) {
  restore.point("gh_set_secret")
  library(reticulate)
  py_file = system.file("py/encrypt_gh_secret.py",package = "GithubActions")
  #py_install("pynacl")
  reticulate::source_python(py_file)

  pub_key = gh_get(paste0("repos/",repo,"/actions/secrets/public-key"))

  key_id = pub_key$key_id
  key_b64 = pub_key$key

  crypt_val_b64 = py_encrypt_gh_secret(key_b64, value)

  #endpoint = repos/OWNER/REPO/actions/secrets/SECRET_NAME
  endpoint = paste0("repos/", repo,"/actions/secrets/", name)

  gh_put(endpoint, values = list(encrypted_value=cript_val_b64, key_id=key_id), pat=pat)
}


#' Set a repository secret
#'
#' Does not yet work.
gh_set_secret_old = function(repo, name, value, pat = Sys.getenv("GITHUB_PAT")) {
  restore.point("gh_set_secret")

  pub_key = gh_get(paste0("repos/",repo,"/actions/secrets/public-key"))

  key_id = pub_key$key_id
  key_b64 = pub_key$key

  library(sodium)
  value_bin = charToRaw(value)
  key_bin =   jsonlite::base64_dec(key_b64)

  crypt_val_bin = sodium::simple_encrypt(value_bin, key_bin)

  library(base64enc)
  crypt_val_b64 = base64enc::base64encode(crypt_val_bin)

  #rawToChar(crypt_val_bin)
  rawToChar(base64enc::base64decode(crypt_val_b64))

  #endpoint = repos/OWNER/REPO/actions/secrets/SECRET_NAME
  endpoint = paste0("repos/", repo,"/actions/secrets/", name)

  gh_put(endpoint, values = list(encrypted_value=cript_val_b64, key_id=key_id), pat=pat)
}

#' Remove a secret from the repository
#'
gh_remove_secret = function(repo, name, pat = Sys.getenv("GITHUB_PAT")) {
  restore.point("gh_remove_secret")
  # /repos/{owner}/{repo}/actions/secrets/{secret_name}
  endpoint = paste0("repos/", repo,"/actions/secrets/", name)
  gh_delete(endpoint, pat)
}

#' Download an artifact generated by a finished job
gh_download_artifact = function(repo, destfile, artifact_id = NULL, pat = gh_pat()) {
  restore.point("gh_download_artifact")

  if (is.null(artifact_id)) {
    artifacts = gh_list_artifacts(repo, pat)
    if (NROW(artifacts)==0) {
      cat("\nNo artifacts found.")
      return(NULL)
    }
    artifact_id = artifacts$id[[1]]
  }


  endpoint = paste0("repos/",repo,"/actions/artifacts/", artifact_id,"/zip")
  res = gh_get(endpoint=endpoint,pat = pat, output="httr")

  if (res$status_code < 300) {
    writeBin(res$content, con = destfile)
    return(invisible(res))
  } else {
    cat("\nCould not retrieve artifact.\n")
    return(res)
  }

}

#' List all artifacts of a repo
gh_list_artifacts = function(repo, pat = gh_pat()) {
  endpoint = paste0("repos/", repo,"/actions/artifacts")
  res = gh_get(endpoint, pat)
  artifacts = res$artifacts
  artifacts
}

gh_put = function(endpoint, values=NULL, pat = Sys.getenv("GITHUB_PAT")) {
  restore.point("gh_put")
  headers = gh_headers(pat, add_content_type = TRUE)
  json.values = jsonlite::toJSON(values,auto_unbox = TRUE)

  httr::PUT(url = gh_url(endpoint), httr::add_headers(.headers=headers), body = json.values)
}

gh_post = function(endpoint, values, pat = Sys.getenv("GITHUB_PAT")) {
  restore.point("gh_post")
  headers = gh_headers(pat, add_content_type = TRUE)
  json.values = jsonlite::toJSON(values,auto_unbox = TRUE)

  httr::POST(url = gh_url(endpoint), httr::add_headers(.headers=headers), body = json.values)
}


gh_delete = function(endpoint, pat = Sys.getenv()) {
  restore.point("gh_delete")
  httr::DELETE(url = gh_url(endpoint), httr::add_headers(.headers=gh_headers(pat)))
}

gh_get = function(endpoint, pat=gh_pat(), output = c("json","text","org", "httr")[1]) {
  restore.point("api")

  if (output == "httr") {
    headers = gh_headers(pat, add_content_type = TRUE)
    res = httr::GET(url = gh_url(endpoint), httr::add_headers(.headers=headers))
    return(res)
  }

  url=paste0("https://api.github.com/", endpoint)

  hx <- curl::handle_setheaders(curl::new_handle(),
    Authorization = paste0("Bearer ", pat),
    Accept =  "application/vnd.github+json",
    "X-GitHub-Api-Version: 2022-11-28"
  )

  req <- curl::curl_fetch_memory(url, handle = hx)
  if (output == "org") return(req)

  content = rawToChar(req$content)
  if (output == "text") return(content)

  jsonlite::fromJSON(content)
}


gh_url = function(endpoint) {
  paste0("https://api.github.com/", endpoint)
}

gh_headers = function(pat=Sys.getenv("GITHUB_PAT"), add_content_type=FALSE) {
  headers = c(
    `Accept` = 'application/vnd.github+json',
    `Authorization` = paste0("Bearer ", pat),
    `X-GitHub-Api-Version` = '2022-11-28'
  )
  if (add_content_type) {
    headers = c(headers,`Content-Type` = 'application/x-www-form-urlencoded')
  }
  headers
}
